
sudo: required
services:
  - docker

before_install:
   - gem install rake

   - docker build -t marcroservecm/docker2-repo2 -f Dockerfile.dev .
   
    

script:
   
  

    





    




    




