sudo: required
services:
  - docker

before_install:
   language: ruby
   rvm:
   - 2.5.0
   - gem install rake
   - docker build -t marcroservecm/docker2-repo2 -f Dockerfile.dev .

script:
    - docker run marcroservecm/docker2-repo2 npm run test -- --coverage
    - bundle install — jobs=3 — retry=3
    - bundle exec rake db:create
    - bundle exec rake db:migrate
    - bundle exec rspec 

