Language: generic
sudo: required

services:

  - docker

before_install:

  
  - gem install bundler
  - bundle install
 


   - docker build -t marcroservecm/docker2-repo2 -f Dockerfile.dev .
   
    


   
  

    





    




    




